version: "3.7"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=schedules
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  spring_boot:
    build: .
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/schedules
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_HOST=postgres_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    restart: unless-stopped
volumes:
  postgres:
  pgadmin: